"""Static dependency analysis for the HOI4 agent runtime.

Scans hoi4_agent/**/*.py for intra-project imports and emits
docs/DEPENDENCY_ANALYSIS.md (module table + mermaid graph + coupling notes).

Run:  .venv\\Scripts\\python.exe devtools\\dependency_graph.py
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from itertools import chain
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGE = ROOT / "hoi4_agent"
OUT = ROOT / "docs" / "DEPENDENCY_ANALYSIS.md"

_FROM_RE = re.compile(r"^\s*from\s+([.\w]+)\s+import", re.M)
_IMPORT_RE = re.compile(r"^\s*import\s+([\w.]+)", re.M)


def module_of(path: Path) -> str:
    rel = path.relative_to(PACKAGE).as_posix()
    return rel[:-3].replace("/", ".") if rel.endswith(".py") else rel


def referenced(rel: str, text: str, modules: dict[str, Path]) -> set[str]:
    """Intra-package modules referenced by an import statement in `text`."""
    out: set[str] = set()
    for m in chain(_FROM_RE.finditer(text), _IMPORT_RE.finditer(text)):
        name = m.group(1)
        if name.startswith("."):
            # Resolve relative imports against the importing module's package.
            depth = len(name) - len(name.lstrip("."))
            base = rel.split(".")
            pkg = base[: len(base) - depth]
            tail = name.lstrip(".")
            candidate = ".".join(pkg + ([tail] if tail else []))
            key = candidate
        else:
            candidate = name
            if not candidate.startswith("hoi4_agent"):
                continue
            key = candidate.removeprefix("hoi4_agent.")
        if key in modules:
            out.add(key)
    return out


def main() -> None:
    modules: dict[str, Path] = {}
    for f in sorted(PACKAGE.rglob("*.py")):
        if "__pycache__" in f.parts or f.parent.name == "tests":
            continue
        modules[module_of(f)] = f

    deps: dict[str, set[str]] = defaultdict(set)
    for key, path in modules.items():
        text = path.read_text(encoding="utf-8", errors="ignore")
        deps[key] = referenced(key, text, modules) - {key}

    fan_out = {k: len(v) for k, v in deps.items()}
    fan_in: dict[str, int] = defaultdict(int)
    for v in deps.values():
        for d in v:
            fan_in[d] += 1

    cycles: list[str] = []
    for a, targets in deps.items():
        for b in targets:
            if a in deps.get(b, set()) and b > a:
                cycles.append(f"{b} <-> {a}")

    lines = [
        "# Dependency Analysis",
        "",
        "Static intra-package imports for `hoi4_agent/`. Generated by "
        "`devtools/dependency_graph.py`.",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for src in sorted(deps):
        for dst in sorted(deps[src]):
            lines.append(f'    {src.replace("_", "_")} --> {dst.replace("_", "_")}')
    lines += ["```", "", "## Module coupling", "",
              "| Module | Depends on (in-package) | Depended on by |", "|---|---|---|"]
    for key in sorted(fan_in, key=lambda k: (-fan_in[k], k)):
        lines.append(f"| `{key}` | {', '.join('`'+d+'`' for d in sorted(deps[key])) or '—'} "
                     f"| {fan_in[key]} |")
    lines += ["", "## Findings", ""]
    hubs = sorted((k for k in fan_in if fan_in[k] >= 4), key=lambda k: -fan_in[k])
    lines.append(f"- **Hub modules** (4+ dependents): {', '.join('`'+h+'`' for h in hubs) or 'none'}."
                 " These are the natural integration points; keep their public APIs small.")
    lines.append(f"- **Circular imports**: {', '.join(cycles) or 'none detected'}.")
    leaves = sorted(k for k in fan_out if fan_out[k] == 0)
    lines.append(f"- **Leaf modules** (no in-package deps): {', '.join('`'+l+'`' for l in leaves) or 'none'}.")
    lines += ["", "## Recommendations", "",
              "1. `agent.py` and `project.py` are the biggest hubs. New features should "
              "extend the planner task graph + generators, not add branches in `agent.run`.",
              "2. `server.py` should stay a thin facade: RPC handlers delegate to "
              "`Agent`/`ProjectExecutor` and never import generators or validators directly.",
              "3. Keep `preview/` free of writes and free of repair/planner imports "
              "(currently clean).",
              "4. If a new subsystem needs `IdentifierIndex`-style lookup, depend on "
              "`identifier_index.py` (STABLE), never on `data/processed` paths directly.",
              "5. Serialization pairs (`ProjectPlan.to_dict/from_dict`, "
              "`Project.to_dict/from_dict`) must stay in sync — a plan-field change "
              "touches exactly those two files plus `server.py` when the field is "
              "user-supplied.",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
